name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH connexion
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TP-AWS }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 with docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            git pull origin ${{ secrets.MAIN_BRANCH }}
            docker-compose -f docker-compose.yml down
            docker system prune -af
            docker image prune -af
            docker-compose up -d --build
          EOF
      - name: Cleanup
        run: rm -rf ~/.ssh